enum ActionTypes {
  GET_CATEGORY_BREADCRUMB_START = "GET_CATEGORY_BREADCRUMB_START",
  GET_CATEGORY_BREADCRUMB_COMPLETED = "GET_CATEGORY_BREADCRUMB_COMPLETED",
  GET_CATEGORY_BREADCRUMB_ERROR = "GET_CATEGORY_BREADCRUMB_ERROR",

  GET_PRODUCT_CARD_START = "GET_PRODUCT_CARD_START",
  GET_PRODUCT_CARD_COMPLETED = "GET_PRODUCT_CARD_COMPLETED",
  GET_PRODUCT_CARD_ERROR = "GET_PRODUCT_CARD_ERROR",

  REMOVE_YOU_ASSESSMENT_START = "REMOVE_YOU_ASSESSMENT_START",
  REMOVE_YOU_ASSESSMENT_COMPLETED = "REMOVE_YOU_ASSESSMENT_COMPLETED",
  REMOVE_YOU_ASSESSMENT_ERROR = "REMOVE_YOU_ASSESSMENT_ERROR",

  CREATE_YOU_ASSESSMENT_START = "CREATE_YOU_ASSESSMENT_START",
  CREATE_YOU_ASSESSMENT_COMPLETED = "CREATE_YOU_ASSESSMENT_COMPLETED",
  CREATE_YOU_ASSESSMENT_ERROR = "CREATE_YOU_ASSESSMENT_ERROR",

  GET_OVERVIEW_EVALUATES_PRODUCT_START = "GET_OVERVIEW_EVALUATES_PRODUCT_START",
  GET_OVERVIEW_EVALUATES_PRODUCT_COMPLETED = "GET_OVERVIEW_EVALUATES_PRODUCT_COMPLETED",
  GET_OVERVIEW_EVALUATES_PRODUCT_ERROR = "GET_OVERVIEW_EVALUATES_PRODUCT_ERROR",

  GET_REVIEW_EVALUATES_PRODUCT_START = "GET_REVIEW_EVALUATES_PRODUCT_START",
  GET_REVIEW_EVALUATES_PRODUCT_COMPLETED = "GET_REVIEW_EVALUATES_PRODUCT_COMPLETED",
  GET_REVIEW_EVALUATES_PRODUCT_ERROR = "GET_REVIEW_EVALUATES_PRODUCT_ERROR",

  LIKE_EVALUATES_PRODUCT_START = "LIKE_EVALUATES_PRODUCT_START",
  LIKE_EVALUATES_PRODUCT_COMPLETED = "LIKE_EVALUATES_PRODUCT_COMPLETED",
  LIKE_EVALUATES_PRODUCT_ERROR = "LIKE_EVALUATES_PRODUCT_ERROR",

  DISLIKE_EVALUATES_PRODUCT_START = "DISLIKE_EVALUATES_PRODUCT_START",
  DISLIKE_EVALUATES_PRODUCT_COMPLETED = "DISLIKE_EVALUATES_PRODUCT_COMPLETED",
  DISLIKE_EVALUATES_PRODUCT_ERROR = "DISLIKE_EVALUATES_PRODUCT_ERROR",

  REPCOMMENT_EVALUATES_PRODUCT_START = "REPCOMMENT_EVALUATES_PRODUCT_START",
  REPCOMMENT_EVALUATES_PRODUCT_COMPLETED = "REPCOMMENT_EVALUATES_PRODUCT_COMPLETED",
  REPCOMMENT_EVALUATES_PRODUCT_ERROR = "REPCOMMENT_EVALUATES_PRODUCT_ERROR",

  GET_REPCOMMENT_EVALUATES_PRODUCT_START = "GET_REPCOMMENT_EVALUATES_PRODUCT_START",
  GET_REPCOMMENT_EVALUATES_PRODUCT_COMPLETED = "GET_REPCOMMENT_EVALUATES_PRODUCT_COMPLETED",
  GET_REPCOMMENT_EVALUATES_PRODUCT_ERROR = "GET_REPCOMMENT_EVALUATES_PRODUCT_ERROR",
}

export default ActionTypes;
