enum ActionTypes {
  WATCH_PAGE_START = "WATCH_PAGE_START",
  WATCH_PAGE_COMPLETED = "WATCH_PAGE_COMPLETED",
  WATCH_PAGE_ERROR = "WATCH_PAGE_ERROR",

  GET_CATEGORY_MAIN_START = "GET_CATEGORY_MAIN_START",
  GET_CATEGORY_MAIN_COMPLETED = "GET_CATEGORY_MAIN_COMPLETED",
  GET_CATEGORY_MAIN_ERROR = "GET_CATEGORY_MAIN_ERROR",

  CREATE_SPECIFICATIONS_START = "CREATE_SPECIFICATIONS_START",
  CREATE_SPECIFICATIONS_COMPLETED = "CREATE_SPECIFICATIONS_COMPLETED",
  CREATE_SPECIFICATIONS_ERROR = "CREATE_SPECIFICATIONS_ERROR",

  GET_NAME_KEY_SPECIFICATIONS_START = "GET_NAME_KEY_SPECIFICATIONS_START",
  GET_NAME_KEY_SPECIFICATIONS_COMPLETED = "GET_NAME_KEY_SPECIFICATIONS_COMPLETED",
  GET_NAME_KEY_SPECIFICATIONS_ERROR = "GET_NAME_KEY_SPECIFICATIONS_ERROR",

  GET_NAME_VALUES_SPECIFICATIONS_START = "GET_NAME_VALUES_SPECIFICATIONS_START",
  GET_NAME_VALUES_SPECIFICATIONS_COMPLETED = "GET_NAME_VALUES_SPECIFICATIONS_COMPLETED",
  GET_NAME_VALUES_SPECIFICATIONS_ERROR = "GET_NAME_VALUES_SPECIFICATIONS_ERROR",

  SEARCH_SPECIFICATIONS_START = "SEARCH_SPECIFICATIONS_START",
  SEARCH_SPECIFICATIONS_COMPLETED = "SEARCH_SPECIFICATIONS_COMPLETED",
  SEARCH_SPECIFICATIONS_ERROR = "SEARCH_SPECIFICATIONS_ERROR",
}

export default ActionTypes;
