enum ActionTypes {
    //#region mở trang
    WATCH_PAGE_ERROR = 'WATCH_PAGE_ERROR',
    //#endregion

    //#region RESOURCE
    LIST_FORM_RESOURCE_START = 'GET_LIST_FORM_RESOURCE_START',
    LIST_FORM_RESOURCE_COMPLETED = 'GET_LIST_FORM_RESOURCE_COMPLETED',
    LIST_FORM_RESOURCE_ERROR = 'GET_LIST_FORM_RESOURCE_ERROR',

    RESOURCE_CREATE_ITEM_START = 'RESOURCE_CREATE_ITEM_START',
    RESOURCE_CREATE_ITEM_COMPLETED = 'RESOURCE_CREATE_ITEM_COMPLETED',
    RESOURCE_CREATE_ITEM_ERROR = 'RESOURCE_CREATE_ITEM_ERROR',

    RESOURCE_EDIT_ITEM_START = 'RESOURCE_EDIT_ITEM_START',
    RESOURCE_EDIT_ITEM_COMPLETED = 'RESOURCE_EDIT_ITEM_COMPLETED',
    RESOURCE_EDIT_ITEM_ERROR = 'RESOURCE_EDIT_ITEM_ERROR',

    RESOURCE_REMOVE_FE_ITEM_START = "RESOURCE_REMOVE_FE_ITEM_START",
    RESOURCE_REMOVE_FE_ITEM_CANCEL = "RESOURCE_REMOVE_FE_ITEM_CANCEL",

    RESOURCE_REMOVE_START = "RESOURCE_REMOVE_START",
    RESOURCE_REMOVE_COMPLETED = "RESOURCE_REMOVE_COMPLETED",
    RESOURCE_REMOVE_ERROR = "RESOURCE_REMOVE_ERROR",

    RESOURCE_EDIT_STATUS_START = "RESOURCE_EDIT_STATUS_START",
    RESOURCE_EDIT_STATUS_COMPLETED = "RESOURCE_EDIT_STATUS_COMPLETED",
    RESOURCE_EDIT_STATUS_ERROR = "RESOURCE_EDIT_STATUS_ERROR",
    //#endregion

    //#region  ATOMIC 
    ATOMIC_LIST_START = "ATOMIC_LIST_START",
    ATOMIC_LIST_COMPLETED = "ATOMIC_LIST_COMPLETED",
    ATOMIC_LIST_ERROR = "ATOMIC_LIST_ERROR",
    //#endregion

    //#region ACTION
    ACTION_LIST_FORM_START = 'ACTION_LIST_FORM_START',
    ACTION_LIST_FORM_COMPLETED = 'ACTION_LIST_FORM_COMPLETED',
    ACTION_LIST_FORM_ERROR = 'ACTION_LIST_FORM_ERROR',

    ACTION_CREATE_ITEM_START = 'ACTION_CREATE_ITEM_START',
    ACTION_CREATE_ITEM_COMPLETED = 'ACTION_CREATE_ITEM_COMPLETED',
    ACTION_CREATE_ITEM_ERROR = 'ACTION_CREATE_ITEM_ERROR',

    ACTION_EDIT_ITEM_START = 'ACTION_EDIT_ITEM_START',
    ACTION_EDIT_ITEM_COMPLETED = 'ACTION_EDIT_ITEM_COMPLETED',
    ACTION_EDIT_ITEM_ERROR = 'ACTION_EDIT_ITEM_ERROR',

    ACTION_REMOVE_FE_ITEM_START = "ACTION_REMOVE_FE_ITEM_START",
    ACTION_REMOVE_FE_ITEM_CANCEL = "ACTION_REMOVE_FE_ITEM_CANCEL",

    ACTION_REMOVE_START = "ACTION_REMOVE_START",
    ACTION_REMOVE_COMPLETED = "ACTION_REMOVE_COMPLETED",
    ACTION_REMOVE_ERROR = "ACTION_REMOVE_ERROR",

    //#endregion

    //#region PERMISSION
    PERMISSION_LIST_FORM_START = 'PERMISSION_LIST_FORM_START',
    PERMISSION_LIST_FORM_COMPLETED = 'PERMISSION_LIST_FORM_COMPLETED',
    PERMISSION_LIST_FORM_ERROR = 'PERMISSION_LIST_FORM_ERROR',

    PERMISSION_CREATE_ITEM_START = 'PERMISSION_CREATE_ITEM_START',
    PERMISSION_CREATE_ITEM_COMPLETED = 'PERMISSION_CREATE_ITEM_COMPLETED',
    PERMISSION_CREATE_ITEM_ERROR = 'PERMISSION_CREATE_ITEM_ERROR',

    PERMISSION_EDIT_ITEM_START = 'PERMISSION_EDIT_ITEM_START',
    PERMISSION_EDIT_ITEM_COMPLETED = 'PERMISSION_EDIT_ITEM_COMPLETED',
    PERMISSION_EDIT_ITEM_ERROR = 'PERMISSION_EDIT_ITEM_ERROR',

    PERMISSION_REMOVE_FE_ITEM_START = "PERMISSION_REMOVE_FE_ITEM_START",
    PERMISSION_REMOVE_FE_ITEM_CANCEL = "PERMISSION_REMOVE_FE_ITEM_CANCEL",

    PERMISSION_REMOVE_START = "PERMISSION_REMOVE_START",
    PERMISSION_REMOVE_COMPLETED = "PERMISSION_REMOVE_COMPLETED",
    PERMISSION_REMOVE_ERROR = "PERMISSION_REMOVE_ERROR",

    //#endregion

    //#region ROLE
    ROLE_LIST_FORM_START = 'ROLE_LIST_FORM_START',
    ROLE_LIST_FORM_COMPLETED = 'ROLE_LIST_FORM_COMPLETED',
    ROLE_LIST_FORM_ERROR = 'ROLE_LIST_FORM_ERROR',

    ROLE_CREATE_ITEM_START = 'ROLE_CREATE_ITEM_START',
    ROLE_CREATE_ITEM_COMPLETED = 'ROLE_CREATE_ITEM_COMPLETED',
    ROLE_CREATE_ITEM_ERROR = 'ROLE_CREATE_ITEM_ERROR',

    ROLE_EDIT_ITEM_START = 'ROLE_EDIT_ITEM_START',
    ROLE_EDIT_ITEM_COMPLETED = 'ROLE_EDIT_ITEM_COMPLETED',
    ROLE_EDIT_ITEM_ERROR = 'ROLE_EDIT_ITEM_ERROR',

    ROLE_REMOVE_FE_ITEM_START = "ROLE_REMOVE_FE_ITEM_START",
    ROLE_REMOVE_FE_ITEM_CANCEL = "ROLE_REMOVE_FE_ITEM_CANCEL",

    ROLE_REMOVE_START = "ROLE_REMOVE_START",
    ROLE_REMOVE_COMPLETED = "ROLE_REMOVE_COMPLETED",
    ROLE_REMOVE_ERROR = "ROLE_REMOVE_ERROR",
    //#endregion

    //#region  RESOURCE_ACTION
    ACTION_RESOURCE_LIST_START ='ACTION_RESOURCE_LIST_START',
    ACTION_RESOURCE_LIST_COMPELETED ='ACTION_RESOURCE_LIST_COMPELETED',
    ACTION_RESOURCE_LIST_ERROR ='ACTION_RESOURCE_LIST_ERROR',

    RESOURCE_ACTION_INSERT_OR_UPDATE_START ='RESOURCE_ACTION_INSERT_OR_UPDATE_START',
    RESOURCE_ACTION_INSERT_OR_UPDATE_COMPELETED ='RESOURCE_ACTION_INSERT_OR_UPDATE_COMPELETED',
    RESOURCE_ACTION_INSERT_OR_UPDATE_ERROR ='RESOURCE_ACTION_INSERT_OR_UPDATE_ERROR',

    //#endregion

    //#region  Action Assignment
    ACTION_ASSIGNMENT_GET_LIST_DATA_START ='ACTION_ASSIGNMENT_GET_LIST_DATA_START',
    ACTION_ASSIGNMENT_GET_LIST_DATA_COMPELETED ='ACTION_ASSIGNMENT_GET_LIST_DATA_COMPELETED',
    ACTION_ASSIGNMENT_GET_LIST_DATA_ERROR ='ACTION_ASSIGNMENT_GET_LIST_DATA_ERROR',

    ACTION_ASSIGNMENT_INSERT_OR_UPDATE_START ='ACTION_ASSIGNMENT_INSERT_OR_UPDATE_START',
    ACTION_ASSIGNMENT_INSERT_OR_UPDATE_COMPELETED ='ACTION_ASSIGNMENT_INSERT_OR_UPDATE_COMPELETED',
    ACTION_ASSIGNMENT_INSERT_OR_UPDATE_ERROR ='ACTION_ASSIGNMENT_INSERT_OR_UPDATE_ERROR',
    //#endregion

    //#region  PermissionAssignment
    PERMISSION_ASSIGNMENT_GET_LIST_DATA_START ='PERMISSION_ASSIGNMENT_GET_LIST_DATA_START',
    PERMISSION_ASSIGNMENT_GET_LIST_DATA_COMPELETED ='PERMISSION_ASSIGNMENT_GET_LIST_DATA_COMPELETED',
    PERMISSION_ASSIGNMENT_GET_LIST_DATA_ERROR ='PERMISSION_ASSIGNMENT_GET_LIST_DATA_ERROR',

    PERMISSION_ASSIGNMENT_INSERT_OR_UPDATE_START ='PERMISSION_ASSIGNMENT_INSERT_OR_UPDATE_START',
    PERMISSION_ASSIGNMENT_INSERT_OR_UPDATE_COMPELETED ='PERMISSION_ASSIGNMENT_INSERT_OR_UPDATE_COMPELETED',
    PERMISSION_ASSIGNMENT_INSERT_OR_UPDATE_ERROR ='PERMISSION_ASSIGNMENT_INSERT_OR_UPDATE_ERROR',
    //#endregion
}

export default ActionTypes;