enum ActionTypes {
    WATCH_PAGE_START = 'WATCH_PAGE_START',
    WATCH_PAGE_COMPLETED = 'WATCH_PAGE_COMPLETED',
    WATCH_PAGE_ERROR = 'WATCH_PAGE_ERROR',

    CREATE_CATEGORY_ADMIN_START = 'CREATE_CATEGORY_ADMIN_START',
    CREATE_CATEGORY_ADMIN_COMPLETED = 'CREATE_CATEGORY_ADMIN_COMPLETED',
    CREATE_CATEGORY_ADMIN_ERROR = 'CREATE_CATEGORY_ADMIN_ERROR',

    GET_CATEGORY_ADMIN_START='GET_CATEGORY_ADMIN_START',
    GET_CATEGORY_ADMIN_COMPLETED='GET_CATEGORY_ADMIN_COMPLETED',
    GET_CATEGORY_ADMIN_ERROR='GET_CATEGORY_ADMIN_ERROR',
}
  
export default ActionTypes;