enum ActionTypes {
    WATCH_PAGE_START = 'WATCH_PAGE_START',
    WATCH_PAGE_COMPLETED = 'WATCH_PAGE_COMPLETED',
    WATCH_PAGE_ERROR = 'WATCH_PAGE_ERROR',

    //#region GET_DATA_ATTRIBUTE_PRODUCT
    GET_DATA_ATTRIBUTE_PRODUCT_START = 'GET_DATA_ATTRIBUTE_PRODUCT_START',
    GET_DATA_ATTRIBUTE_PRODUCT_COMPLETED = 'GET_DATA_ATTRIBUTE_PRODUCT_COMPLETED',
    GET_DATA_ATTRIBUTE_PRODUCT_ERROR = 'GET_DATA_ATTRIBUTE_PRODUCT_ERROR',
    //#endregion

    //#region CREATE_ATTRIBUTE_PRODUCT
    CREATE_ATTRIBUTE_PRODUCT_START = 'CREATE_ATTRIBUTE_PRODUCT_START',
    CREATE_ATTRIBUTE_PRODUCT_COMPLETED = 'CREATE_ATTRIBUTE_PRODUCT_COMPLETED',
    CREATE_ATTRIBUTE_PRODUCT_ERROR = 'CREATE_ATTRIBUTE_PRODUCT_ERROR',
    //#endregion
}

export default ActionTypes;