enum ActionTypes {
    GET_LIST_ERROR_SYSTEM_START="GET_LIST_ERROR_SYSTEM_START",
    GET_LIST_ERROR_SYSTEM_COMPLETED="GET_LIST_ERROR_SYSTEM_COMPLETED",
    GET_LIST_ERROR_SYSTEM_ERROR="GET_LIST_ERROR_SYSTEM_ERROR",
    FIX_ERROR_SYSTEM_START = "FIX_ERROR_SYSTEM_START",
    FIX_ERROR_SYSTEM_COMPLETED = "FIX_ERROR_SYSTEM_COMPLETED",
    FIX_ERROR_SYSTEM_ERROR = "FIX_ERROR_SYSTEM_ERROR",
}
  
export default ActionTypes;