enum ActionTypes {
    //#region  GET_CATEGORY_ADMIN
    GET_CATEGORY_ADMIN_START='GET_CATEGORY_ADMIN_START',
    GET_CATEGORY_ADMIN_COMPLETED='GET_CATEGORY_ADMIN_COMPLETED',
    GET_CATEGORY_ADMIN_ERROR='GET_CATEGORY_ADMIN_ERROR',
    //#endregion
    
    WATCH_PAGE_START = 'WATCH_PAGE_START',
    WATCH_PAGE_COMPLETED = 'WATCH_PAGE_COMPLETED',
    WATCH_PAGE_ERROR = 'WATCH_PAGE_ERROR',
}
  
export default ActionTypes;