enum ActionTypes {
    LOGIN_REQUEST_LOGIN_START = 'LOGIN_REQUEST_LOGIN_START',
    LOGIN_REQUEST_LOGIN_COMPLETED = 'LOGIN_REQUEST_LOGIN_COMPLETED',
    LOGIN_REQUEST_LOGIN_ERROR = 'LOGIN_REQUEST_LOGIN_ERROR',

    //#region REGISTRATION_ACCOUNT_BASIC
    REGISTRATION_ACCOUNT_BASIC_START = 'REGISTRATION_ACCOUNT_BASIC_START',
    REGISTRATION_ACCOUNT_BASIC_COMPLETED = 'REGISTRATION_ACCOUNT_BASIC_COMPLETED',
    REGISTRATION_ACCOUNT_BASIC_ERROR = 'REGISTRATION_ACCOUNT_BASIC_ERROR',
    //#endregion
}

export default ActionTypes;