enum ActionTypes {
    LOGIN_SHOW_START = 'LOGIN_SHOW_START',
    LOGIN_SHOW_COMPLETED = 'LOGIN_SHOW_COMPLETED',
    LOGIN_SHOW_ERROR = 'LOGIN_SHOW_ERROR',
    LOGIN_REQUEST_LOGIN_START = 'LOGIN_REQUEST_LOGIN_START',
    LOGIN_REQUEST_LOGIN_COMPLETED = 'LOGIN_REQUEST_LOGIN_COMPLETED',
    LOGIN_REQUEST_LOGIN_ERROR = 'LOGIN_REQUEST_LOGIN_ERROR'
}
  
export default ActionTypes;