enum ActionTypes {

  //#region GET_USER_PROFILE
  GET_USER_PROFILE_START = 'GET_USER_PROFILE_START',
  GET_USER_PROFILE_COMPLETED = 'GET_USER_PROFILE_COMPLETED',
  GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR',
  //#endregion

  //#region GET_RESOURCE
  GET_RESOURCE_START = 'GET_RESOURCE_START',
  GET_RESOURCE_COMPLETED = 'GET_RESOURCE_COMPLETED',
  GET_RESOURCE_ERROR = 'GET_RESOURCE_ERROR',
  //#endregion
  //#region DELETE_RESOURCE
  DELETE_RESOURCE_START = 'DELETE_RESOURCE_START',
  DELETE_RESOURCE_COMPLETED = 'DELETE_RESOURCE_COMPLETED',
  DELETE_RESOURCE_ERROR = 'DELETE_RESOURCE_ERROR',
  //#endregion
  //#region EDIT_STATUS_RESOURCE
  EDIT_STATUS_RESOURCE_START = 'EDIT_STATUS_RESOURCE_START',
  EDIT_STATUS_RESOURCE_COMPLETED = 'EDIT_STATUS_RESOURCE_COMPLETED',
  EDIT_STATUS_RESOURCE_ERROR = 'EDIT_STATUS_RESOURCE_ERROR',
  //#endregion
  //#region INSERT_OR_UPDATE_RESOURCE
  INSERT_OR_UPDATE_RESOURCE_START = 'INSERT_OR_UPDATE_RESOURCE_START',
  INSERT_OR_UPDATE_RESOURCE_COMPLETED = 'INSERT_OR_UPDATE_RESOURCE_COMPLETED',
  INSERT_OR_UPDATE_RESOURCE_ERROR = 'INSERT_OR_UPDATE_RESOURCE_ERROR',
  //#endregion

  //#region GET_ATOMIC
  GET_ATOMIC_START = 'GET_ATOMIC_START',
  GET_ATOMIC_COMPLETED = 'GET_ATOMIC_COMPLETED',
  GET_ATOMIC_ERROR = 'GET_ATOMIC_ERROR',
  //#endregion
  //#region DELETE_ATOMIC
  DELETE_ATOMIC_START = 'DELETE_ATOMIC_START',
  DELETE_ATOMIC_COMPLETED = 'DELETE_ATOMIC_COMPLETED',
  DELETE_ATOMIC_ERROR = 'DELETE_ATOMIC_ERROR',
  //#endregion
  //#region EDIT_STATUS_ATOMIC
  EDIT_STATUS_ATOMIC_START = 'EDIT_STATUS_ATOMIC_START',
  EDIT_STATUS_ATOMIC_COMPLETED = 'EDIT_STATUS_ATOMIC_COMPLETED',
  EDIT_STATUS_ATOMIC_ERROR = 'EDIT_STATUS_ATOMIC_ERROR',
  //#endregion
  //#region INSERT_OR_UPDATE_ATOMIC
  INSERT_OR_UPDATE_ATOMIC_START = 'INSERT_OR_UPDATE_ATOMIC_START',
  INSERT_OR_UPDATE_ATOMIC_COMPLETED = 'INSERT_OR_UPDATE_ATOMIC_COMPLETED',
  INSERT_OR_UPDATE_ATOMIC_ERROR = 'INSERT_OR_UPDATE_ATOMIC_ERROR',
  //#endregion
  //#region SUMMARY_ATOMIC
  SUMMARY_ATOMIC_START = 'SUMMARY_ATOMIC_START',
  SUMMARY_ATOMIC_COMPLETED = 'SUMMARY_ATOMIC_COMPLETED',
  SUMMARY_ATOMIC_ERROR = 'SUMMARY_ATOMIC_ERROR',
  //#endregion

  //#region GET_PERMISSION
  GET_PERMISSION_START = 'GET_PERMISSION_START',
  GET_PERMISSION_COMPLETED = 'GET_PERMISSION_COMPLETED',
  GET_PERMISSION_ERROR = 'GET_PERMISSION_ERROR',
  //#endregion
  //#region DELETE_PERMISSION
  DELETE_PERMISSION_START = 'DELETE_PERMISSION_START',
  DELETE_PERMISSION_COMPLETED = 'DELETE_PERMISSION_COMPLETED',
  DELETE_PERMISSION_ERROR = 'DELETE_PERMISSION_ERROR',
  //#endregion
  //#region EDIT_STATUS_PERMISSION
  EDIT_STATUS_PERMISSION_START = 'EDIT_STATUS_PERMISSION_START',
  EDIT_STATUS_PERMISSION_COMPLETED = 'EDIT_STATUS_PERMISSION_COMPLETED',
  EDIT_STATUS_PERMISSION_ERROR = 'EDIT_STATUS_PERMISSION_ERROR',
  //#endregion
  //#region INSERT_OR_UPDATE_PERMISSION
  INSERT_OR_UPDATE_PERMISSION_START = 'INSERT_OR_UPDATE_PERMISSION_START',
  INSERT_OR_UPDATE_PERMISSION_COMPLETED = 'INSERT_OR_UPDATE_PERMISSION_COMPLETED',
  INSERT_OR_UPDATE_PERMISSION_ERROR = 'INSERT_OR_UPDATE_PERMISSION_ERROR',
  //#endregion
  //#region SEARCH_SUMMARY_PERMISSION
  SEARCH_SUMMARY_PERMISSION_START = 'SEARCH_SUMMARY_PERMISSION_START',
  SEARCH_SUMMARY_PERMISSION_COMPLETED = 'SEARCH_SUMMARY_PERMISSION_COMPLETED',
  SEARCH_SUMMARY_PERMISSION_ERROR = 'SEARCH_SUMMARY_RESOURCE_ERROR',
  //#endregion

  //#region GET_ROLE
  GET_ROLE_START = 'GET_ROLE_START',
  GET_ROLE_COMPLETED = 'GET_ROLE_COMPLETED',
  GET_ROLE_ERROR = 'GET_ROLE_ERROR',
  //#endregion
  //#region DELETE_ROLE
  DELETE_ROLE_START = 'DELETE_ROLE_START',
  DELETE_ROLE_COMPLETED = 'DELETE_ROLE_COMPLETED',
  DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR',
  //#endregion
  //#region EDIT_STATUS_ROLE
  EDIT_STATUS_ROLE_START = 'EDIT_STATUS_ROLE_START',
  EDIT_STATUS_ROLE_COMPLETED = 'EDIT_STATUS_ROLE_COMPLETED',
  EDIT_STATUS_ROLE_ERROR = 'EDIT_STATUS_ROLE_ERROR',
  //#endregion
  //#region INSERT_OR_UPDATE_ROLE
  INSERT_OR_UPDATE_ROLE_START = 'INSERT_OR_UPDATE_ROLE_START',
  INSERT_OR_UPDATE_ROLE_COMPLETED = 'INSERT_OR_UPDATE_ROLE_COMPLETED',
  INSERT_OR_UPDATE_ROLE_ERROR = 'INSERT_OR_UPDATE_ROLE_ERROR',
  //#endregion
  //#region SEARCH_SUMMARY_ROLE
  SEARCH_SUMMARY_ROLE_START = 'SEARCH_SUMMARY_ROLE_START',
  SEARCH_SUMMARY_ROLE_COMPLETED = 'SEARCH_SUMMARY_ROLE_COMPLETED',
  SEARCH_SUMMARY_ROLE_ERROR = 'SEARCH_SUMMARY_ROLE_ERROR',
  //#endregion

  //#region GET_SUBJECT
  GET_SUBJECT_START = 'GET_SUBJECT_START',
  GET_SUBJECT_COMPLETED = 'GET_SUBJECT_COMPLETED',
  GET_SUBJECT_ERROR = 'GET_SUBJECT_ERROR',
  //#endregion
  //#region DELETE_SUBJECT
  DELETE_SUBJECT_START = 'DELETE_SUBJECT_START',
  DELETE_SUBJECT_COMPLETED = 'DELETE_SUBJECT_COMPLETED',
  DELETE_SUBJECT_ERROR = 'DELETE_SUBJECT_ERROR',
  //#endregion
  //#region EDIT_STATUS_SUBJECT
  EDIT_STATUS_SUBJECT_START = 'EDIT_STATUS_SUBJECT_START',
  EDIT_STATUS_SUBJECT_COMPLETED = 'EDIT_STATUS_SUBJECT_COMPLETED',
  EDIT_STATUS_SUBJECT_ERROR = 'EDIT_STATUS_SUBJECT_ERROR',
  //#endregion
  //#region INSERT_OR_UPDATE_SUBJECT
  INSERT_OR_UPDATE_SUBJECT_START = 'INSERT_OR_UPDATE_SUBJECT_START',
  INSERT_OR_UPDATE_SUBJECT_COMPLETED = 'INSERT_OR_UPDATE_SUBJECT_COMPLETED',
  INSERT_OR_UPDATE_SUBJECT_ERROR = 'INSERT_OR_UPDATE_SUBJECT_ERROR',
  //#endregion

}

export default ActionTypes;