enum ActionTypes {

  //#region GET_RESOURCE
  GET_RESOURCE_START = 'GET_RESOURCE_START',
  GET_RESOURCE_COMPLETED = 'GET_RESOURCE_COMPLETED',
  GET_RESOURCE_ERROR = 'GET_RESOURCE_ERROR',
  //#endregion
  //#region DELETE_RESOURCE
  DELETE_RESOURCE_START = 'DELETE_RESOURCE_START',
  DELETE_RESOURCE_COMPLETED = 'DELETE_RESOURCE_COMPLETED',
  DELETE_RESOURCE_ERROR = 'DELETE_RESOURCE_ERROR',
  //#endregion
  //#region EDIT_STATUS_RESOURCE
  EDIT_STATUS_RESOURCE_START = 'EDIT_STATUS_RESOURCE_START',
  EDIT_STATUS_RESOURCE_COMPLETED = 'EDIT_STATUS_RESOURCE_COMPLETED',
  EDIT_STATUS_RESOURCE_ERROR = 'EDIT_STATUS_RESOURCE_ERROR',
  //#endregion
  //#region INSERT_OR_UPDATE_RESOURCE
  INSERT_OR_UPDATE_RESOURCE_START = 'INSERT_OR_UPDATE_RESOURCE_START',
  INSERT_OR_UPDATE_RESOURCE_COMPLETED = 'INSERT_OR_UPDATE_RESOURCE_COMPLETED',
  INSERT_OR_UPDATE_RESOURCE_ERROR = 'INSERT_OR_UPDATE_RESOURCE_ERROR',
  //#endregion

  //#region GET_ATOMIC
  GET_ATOMIC_START = 'GET_ATOMIC_START',
  GET_ATOMIC_COMPLETED = 'GET_ATOMIC_COMPLETED',
  GET_ATOMIC_ERROR = 'GET_ATOMIC_ERROR',
  //#endregion
  //#region DELETE_ATOMIC
  DELETE_ATOMIC_START = 'DELETE_ATOMIC_START',
  DELETE_ATOMIC_COMPLETED = 'DELETE_ATOMIC_COMPLETED',
  DELETE_ATOMIC_ERROR = 'DELETE_ATOMIC_ERROR',
  //#endregion
  //#region EDIT_STATUS_ATOMIC
  EDIT_STATUS_ATOMIC_START = 'EDIT_STATUS_ATOMIC_START',
  EDIT_STATUS_ATOMIC_COMPLETED = 'EDIT_STATUS_ATOMIC_COMPLETED',
  EDIT_STATUS_ATOMIC_ERROR = 'EDIT_STATUS_ATOMIC_ERROR',
  //#endregion
  //#region INSERT_OR_UPDATE_ATOMIC
  INSERT_OR_UPDATE_ATOMIC_START = 'INSERT_OR_UPDATE_ATOMIC_START',
  INSERT_OR_UPDATE_ATOMIC_COMPLETED = 'INSERT_OR_UPDATE_ATOMIC_COMPLETED',
  INSERT_OR_UPDATE_ATOMIC_ERROR = 'INSERT_OR_UPDATE_ATOMIC_ERROR',
  //#endregion

}

export default ActionTypes;