enum ActionTypes {

  //#region CREATE_SPECIFICATIONS_START 
  CREATE_SPECIFICATIONS_START = 'CREATE_SPECIFICATIONS_START',
  CREATE_SPECIFICATIONS_COMPLETED = "CREATE_SPECIFICATIONS_COMPLETED",
  CREATE_SPECIFICATIONS_ERROR = "CREATE_SPECIFICATIONS_ERROR",
  //#endregion

  //#region CATEGORY_MAP_START
  CATEGORY_MAP_START = "CATEGORY_MAP_START",
  CATEGORY_MAP_COMPLETED = "CATEGORY_MAP_COMPLETED",
  CATEGORY_MAP_ERROR = "CATEGORY_MAP_ERROR",
  //#endregion

  //#region SPECIFICATIONS_GET_PAGE_LIST 
  SPECIFICATIONS_GET_PAGE_LIST_START = "SPECIFICATIONS_GET_PAGE_LIST_START",
  SPECIFICATIONS_GET_PAGE_LIST_COMPLETED = "SPECIFICATIONS_GET_PAGE_LIST_COMPLETED",
  SPECIFICATIONS_GET_PAGE_LIST_ERROR = "SPECIFICATIONS_GET_PAGE_LIST_ERROR",
  //#endregion

}
export default ActionTypes;