enum ConstTypes{
    ID_CATEGORY = "ID_CATEGORY",
    NAME_CATEGORY = "NAME_CATEGORY",
    URL_CATEGORY = "URL_CATEGORY",
    ICON_CATEGORY = "ICON_CATEGORY",
    LEVEL_CATEGORY = "LEVEL_CATEGORY",
    MAIN_CATEGORY = "MAIN_CATEGORY",
    NUMBER_CATEGORY = "NUMBER_CATEGORY",
    ENABLED_CATEGORY = "ENABLED_CATEGORY",
    CREATE_DATE_UTC_CATEGORY = "CREATE_DATE_UTC_CATEGORY",
    UPDATE_DATE_UTC_CATEGORY = "UPDATE_DATE_UTC_CATEGORY",
    

}
export default ConstTypes;