enum ActionTypes {

  //#region PRO_ATTR_TYPE_UNIT
  PRO_ATTR_TYPE_UNIT_START = 'PRO_ATTR_TYPE_UNIT_START',
  PRO_ATTR_TYPE_UNIT_COMPLETED = 'PRO_ATTR_TYPE_UNIT_COMPLETED',
  PRO_ATTR_TYPE_TRADEMARK_COMPLETED = 'PRO_ATTR_TYPE_TRADEMARK_COMPLETED',
  PRO_ATTR_TYPE_ATTRIBUTE_COMPLETED = "PRO_ATTR_TYPE_ATTRIBUTE_COMPLETED",
  PRO_ATTR_TYPE_UNIT_ERROR = 'PRO_ATTR_TYPE_UNIT_ERROR',
  //#endregion

  //#region GET_CATEGORY_MAIN 
  GET_CATEGORY_MAIN_START = "GET_CATEGORY_MAIN_START",
  GET_CATEGORY_MAIN_COMPLETED = "GET_CATEGORY_MAIN_COMPLETED",
  GET_CATEGORY_MAIN_ERROR = "GET_CATEGORY_MAIN_ERROR",
  //#endregion

  //#region READ_FULL_ALBUM_PRODUCT 
  READ_FULL_ALBUM_PRODUCT_START = "READ_FULL_ALBUM_PRODUCT_START",
  READ_FULL_ALBUM_PRODUCT_COMPLETED = "READ_FULL_ALBUM_PRODUCT_COMPLETED",
  READ_FULL_ALBUM_PRODUCT_ERROR = "READ_FULL_ALBUM_PRODUCT_ERROR",
  //#endregion

  //#region GET_SPECIFI_CATEGORY 
  GET_SPECIFI_CATEGORY_START = "GET_SPECIFI_CATEGORY_START",
  GET_SPECIFI_CATEGORY_COMPLETED = "GET_SPECIFI_CATEGORY_COMPLETED",
  GET_SPECIFI_CATEGORY_ERROR = "GET_SPECIFI_CATEGORY_ERROR",
  //#endregion

  //#region SET_PRODUCT_DTOS 
  SET_PRODUCT_DTOS = "SET_PRODUCT_DTOS",
  //#endregion

  //#region CREATE_PRODUCT 
  CREATE_PRODUCT_START = "CREATE_PRODUCT_START",
  CREATE_PRODUCT_COMPLETED = "CREATE_PRODUCT_COMPLETED",
  CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR",
  //#endregion
}

export default ActionTypes;
