enum ActionTypes {
  WATCH_PAGE_START = "WATCH_PAGE_START",
  WATCH_PAGE_COMPLETED = "WATCH_PAGE_COMPLETED",
  WATCH_PAGE_ERROR = "WATCH_PAGE_ERROR",

  GET_CATEGORY_MAIN_START = "GET_CATEGORY_MAIN_START",
  GET_CATEGORY_MAIN_COMPLETED = "GET_CATEGORY_MAIN_COMPLETED",
  GET_CATEGORY_MAIN_ERROR = "GET_CATEGORY_MAIN_ERROR",

  READ_FULL_ALBUM_PRODUCT_START = "READ_FULL_ALBUM_PRODUCT_START",
  READ_FULL_ALBUM_PRODUCT_COMPLETED = "READ_FULL_ALBUM_PRODUCT_COMPLETED",
  READ_FULL_ALBUM_PRODUCT_ERROR = "READ_FULL_ALBUM_PRODUCT_ERROR",

  GET_SPECIFI_CATEGORY_START = "GET_SPECIFI_CATEGORY_START",
  GET_SPECIFI_CATEGORY_COMPLETED = "GET_SPECIFI_CATEGORY_COMPLETED",
  GET_SPECIFI_CATEGORY_ERROR = "GET_SPECIFI_CATEGORY_ERROR",

  GET_SPECIFI_CATEGORY_UNIT_START = "GET_SPECIFI_CATEGORY_UNIT_START",
  GET_SPECIFI_CATEGORY_UNIT_COMPLETED = "GET_SPECIFI_CATEGORY_UNIT_COMPLETED",
  GET_SPECIFI_CATEGORY_UNIT_ERROR = "GET_SPECIFI_CATEGORY_UNIT_ERROR",
  SET_PRODUCT_DTOS = "SET_PRODUCT_DTOS",

  CREATE_PRODUCT_START = "CREATE_PRODUCT_START",
  CREATE_PRODUCT_COMPLETED = "CREATE_PRODUCT_COMPLETED",
  CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR",
}

export default ActionTypes;
