enum ActionTypes {
  GET_CATEGORY_BREADCRUMB_START = "GET_CATEGORY_BREADCRUMB_START",
  GET_CATEGORY_BREADCRUMB_COMPLETED = "GET_CATEGORY_BREADCRUMB_COMPLETED",
  GET_CATEGORY_BREADCRUMB_ERROR = "GET_CATEGORY_BREADCRUMB_ERROR",
}

export default ActionTypes;
