enum ActionTypes {
  //#region  GET_CATEGORY_BREADCRUMB 
    GET_CATEGORY_BREADCRUMB_START = "GET_CATEGORY_BREADCRUMB_START",
  GET_CATEGORY_BREADCRUMB_COMPLETED = "GET_CATEGORY_BREADCRUMB_COMPLETED",
  GET_CATEGORY_BREADCRUMB_ERROR = "GET_CATEGORY_BREADCRUMB_ERROR",
  //#endregion
  //#region GET_BASIC_PRODUCT_CART
  GET_BASIC_PRODUCT_CART_START = 'GET_BASIC_PRODUCT_CART_START',
  GET_BASIC_PRODUCT_CART_COMPLETED = 'GET_BASIC_PRODUCT_CART_COMPLETED',
  GET_BASIC_PRODUCT_CART_ERROR = 'GET_BASIC_PRODUCT_CART_ERROR',
  //#endregion

}

export default ActionTypes;
